apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator
  namespace: akena-dev
  labels:
    app: akena-orchestrator
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/part-of: akena
    environment: dev
  annotations:
    # Uncomment and set ARN when using IRSA (IAM Roles for Service Accounts) in EKS:
    # eks.amazonaws.com/role-arn: arn:aws:iam::429104603340:role/akena-orchestrator-role
