apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: akena-dev
  labels:
    app: akena-orchestrator
    agentic.io/agent-type: orchestrator
    agentic.io/agent-name: orchestrator
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/part-of: akena
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: akena-orchestrator
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
